# Lints, builds, and tests mooltipage.
# Based on template node.js action, for more information see https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions.
# Please note - commits including this file cannot be pushed from some IDEs (including all JetBrains products).
# As a workaround, push the commit using the git CLI.

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Builds, lints, and tests code.
  build-all:
    name: Build and test project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Run all tests
      run: npm test
    - name: Lint code
      run: npm run lint

  # Upload artifacts
  # This runs one final build (without a matrix) to produce compiled output, then uploads it.
  dist:
    name: Generate code artifacts
    runs-on: ubuntu-latest
    needs: build-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Generate documentation
      run: npm run docs
    - name: Upload code artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mooltipage-dist
        path: |
          dist/
          package.json
          package-lock.json
          LICENSE
          README.md
        if-no-files-found: error